[package]
name = "predator-sense"
version = "0.2.45-preview"
edition = "2021"
description = "Predator Sense for Linux - Hardware control for Acer gaming laptops"
license = "GPL-3.0"
authors = ["Cleyton"]

[dependencies]
gtk4 = "0.9"
libadwaita = { version = "0.7", features = ["v1_5"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dirs = "5"
libc = "0.2"
predator-sense-protocol = { path = "protocol" }
ureq = { version = "2", default-features = false, features = ["json"] }
